import type {Report} from "./ReportTable"

export const reports: Report[] = [
    { id: 1, user: "Alice", avatar: "👩", title: "Monthly Sales Report", category: "Finance", date: "2025-11-23", severity: "High", severityColor: "red", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 2, user: "Charlie", avatar: "👨", title: "Quarterly Budget Review", category: "Finance", date: "2025-11-22", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 3, user: "Bob", avatar: "👨", title: "Bug Fix Deployment", category: "Development", date: "2025-11-20", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 4, user: "Diana", avatar: "👩", title: "New Feature Implementation", category: "Development", date: "2025-11-18", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 5, user: "Eve", avatar: "👩", title: "Server Maintenance", category: "IT", date: "2025-11-17", severity: "High", severityColor: "red", status: "Completed" },
    { id: 6, user: "Frank", avatar: "👨", title: "Customer Feedback Analysis", category: "Support", date: "2025-11-15", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 7, user: "Grace", avatar: "👩", title: "Security Audit", category: "IT", date: "2025-11-14", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 8, user: "Henry", avatar: "👨", title: "Website Optimization", category: "Marketing", date: "2025-11-13", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 9, user: "Ivy", avatar: "👩", title: "Social Media Campaign", category: "Marketing", date: "2025-11-12", severity: "Low", severityColor: "green", status: "Pending" },
    { id: 10, user: "Jack", avatar: "👨", title: "Database Migration", category: "IT", date: "2025-11-10", severity: "High", severityColor: "red", status: "Pending" },
    { id: 11, user: "Kelly", avatar: "👩", title: "Bug Triage Meeting", category: "Development", date: "2025-11-09", severity: "Medium", severityColor: "orange", status: "Completed" },
    { id: 12, user: "Leo", avatar: "👨", title: "Financial Forecast", category: "Finance", date: "2025-11-07", severity: "High", severityColor: "red", status: "Pending" },
    { id: 13, user: "Mia", avatar: "👩", title: "UI/UX Redesign", category: "Design", date: "2025-11-06", severity: "Medium", severityColor: "orange", status: "In Progress" },
    { id: 14, user: "Nick", avatar: "👨", title: "Client Support Tickets", category: "Support", date: "2025-11-05", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 15, user: "Olivia", avatar: "👩", title: "Performance Review", category: "HR", date: "2025-11-04", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 16, user: "Paul", avatar: "👨", title: "New Employee Onboarding", category: "HR", date: "2025-11-03", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 17, user: "Quinn", avatar: "👩", title: "Server Downtime Report", category: "IT", date: "2025-11-02", severity: "High", severityColor: "red", status: "In Progress" },
    { id: 18, user: "Ryan", avatar: "👨", title: "Feature Request Evaluation", category: "Development", date: "2025-11-01", severity: "Medium", severityColor: "orange", status: "Pending" },
    { id: 19, user: "Sophia", avatar: "👩", title: "Customer Satisfaction Survey", category: "Support", date: "2025-10-30", severity: "Low", severityColor: "green", status: "Completed" },
    { id: 20, user: "Tom", avatar: "👨", title: "SEO Analysis", category: "Marketing", date: "2025-10-29", severity: "Medium", severityColor: "orange", status: "Pending" },
];
